# Generated by Django 3.0.7 on 2022-03-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
